#!/usr/bin/env perl
use strict;
use warnings;
use autodie;
use File::Path qw(make_path);

my $content = "testinput\n" x 1000000;

make_path('input');

for my $i (0..2) {
  open my $fh, '>', "input/test$i";
  print $fh $content;
  close $fh;
}
