#!/usr/bin/env perl
use strict;
use warnings;
use autodie;
use File::Path qw(make_path);

make_path('input');

my $small = "testinput\n" x 10;
my $medium = "testinput\n" x 1000000;
my $huge = "testinput\n" x 1000000000;

for my $i (0..2) {
  open my $fh, '>', "input/smallinput$i";
  print $fh $small;
  close $fh;
}
for my $i (0..2) {
  open my $fh, '>', "input/input$i";
  print $fh $medium;
  close $fh;
}
for my $i (0..2) {
  open my $fh, '>', "input/hugeinput$i";
  print $fh $huge;
  close $fh;
}
